#!/bin/bash

flags=(
    "-Ofast" 
    "-march=native" 
    "-Wall"
)

libs=(
    "-lm"
    "-lpthread"
    "-lGL"
    "-lglfw"
    "-lrt"
    "-ldl"
    "-lX11"
    "-lxcb"
    "-lXau"
)

opencl=(
    "-DUSE_OPENCL=1" 
    "-DCL_TARGET_OPENCL_VERSION=300" 
    "-lOpenCL"
)

gcc "./main.c" -o "./pwrt" "${flags[@]}" "${libs[@]}" # "${opencl[@]}"